# Generated by Django 6.0.1 on 2026-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
