# Generated by Django 6.0 on 2026-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_image_post_likes_post_links_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='links',
        ),
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.ManyToManyField(blank=True, to='core.link'),
        ),
    ]
