# Generated by Django 6.0 on 2026-01-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_link_remove_post_links_post_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='links',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
